### PR TITLE
feat: Allow to have pending checks

### LINKED ISSUE #454: Set check status to pending when the only thing failing is approvals
When the only failing check is of type approval, would be nice to set the check status as pending.
Like in this example:
Screenshot 2021-01-04 at 15 32 50

### PR DESCRIPTION
**Pull request by diegomarangoni**
Fixes #454

This PR introduces a new feature that allows having `checks` with status `in_progress`.

### CODE REVIEW

**Comment by shine2lay** [comment]
@diegomarangoni Instead of forcing this particular type of behavior on all users, i think this can be achieved through the config. maybe something like this:

``` 
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'check labels if in master base branch'
    validate:
      - do: approvals
        required:
          reviewers: [ 'shineTest' ]
    fail:
      - do: checks
        state: 'in_progress'
        title: 'Awaiting Approval'
``` 

wdyt?

EDIT: i tested this, we do need to change a couple lines in order to support this use case.

**Comment by diegomarangoni** [comment]
@shine2lay I tested your suggestion and is working pretty fine.

> EDIT: i tested this, we do need to change a couple lines in order to support this use case.

what exactly didn't work?
I used the following config:

```
---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        min:
          count: 1
          message: 'At least 1 developer must approve this PR to merge'
        limit:
          teams: ['@myorg/myteam']
        block:
          changes_requested: true
          message: 'To merge this PR, you must complete the Change Requests'
    fail:
      - do: checks
        state: 'in_progress'
        status: null
        payload:
          title: 'Awaiting approval'
          summary: 'Someone from @myorg/myteam must approve this PR'
```

As far as I understand from github docs, check fields `conclusion` and `completed_at` must not be present when the status is NOT `completed`, but it seems to be working fine.

**Comment by diegomarangoni** [comment]
I updated my PR and changed my approach a bit...
Now, I just removing fields `conclusion` and `completed_at` from the request, but only when the status is **NOT** `completed`.

This fixes and now @shine2lay suggested scenario is working properly

**Review by shine2lay — APPROVED** [review]

**Comment by diegomarangoni** [comment]
hey @shine2lay, can I get this PR merged?

**Comment by shine2lay** [comment]
@diegomarangoni yeah, we are fixing the github action flows for release first, since it's giving error when we merge into master. after that we'll merge this in.

**Pull request merged**
