### PR TITLE
fix: don't throw error if required status is not done

### LINKED ISSUE #386: merge action: add check for required status before attempting to merge
We are not checking required statuses currently before merging, as a result, when a new commit is pushed to PR and other required status (e.g circle ci) not finished, it'll throw error

### PR DESCRIPTION
**Pull request by shine2lay**
There weren't any API to check if all required status is done so the solution implemented here is to just not throw error if we see this specific type of error

### CODE REVIEW

**Comment by samj1912** [comment]
This currently also fails in case one of the required branch checks is that the branch should be up to date or if the branch needs reviewers.

**Comment by samj1912** [comment]
We should be checking for https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-the-combined-status-for-a-specific-reference, I can make a PR soon.

**Review by jusx — APPROVED** [review]

**Comment by jusx** [comment]
@samj1912 Great catch. Looking forward to your PR.

**Comment by shine2lay** [comment]
@jusx @samj1912 I'll merge this in for a temporary solution, left the issue open for when you open your PR.

**Pull request merged**
