### PR TITLE
chore: Async Options

### PR DESCRIPTION
**Pull request by iammuho**
Issue: https://github.com/mergeability/mergeable/issues/480

### CODE REVIEW

**Comment by jusx** [comment]
@iammuho Looks like the smoke test is failing. Could you please resolve?

**Comment by iammuho** [comment]
Hey @jusx, fixed !

**Review by jusx — COMMENTED** [review]
This LGTM -- @shine2lay you should probably review this as well.

**Review by shine2lay — APPROVED** [review]
LGTM

**Pull request merged**
