### PR TITLE
chore(deps): bump standard to latest v16.0.3 available version

### PR DESCRIPTION
**Pull request by quike**
- Bumps jest from 11.0.0 to 16.0.3: Current v11.0.0 was released over 2 years ago

https://www.npmjs.com/package/standard/v/16.0.3
https://www.npmjs.com/package/standard/v/11.0.1

### CODE REVIEW

**Comment by quike** [comment]
```
❯ npm run lint

> mergeable@2.0.0 lint /Users/empirl/Workspace/repo/github/mergeability/mergeable
> standard --fix

standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/__fixtures__/unit/helper.js:91:24: Expected newline between test and consequent of ternary expression.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/__fixtures__/unit/helper.js:91:45: Expected newline between consequent and alternate of ternary expression.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/actions/close.js:26:23: Array.prototype.map() expects a return value from arrow function.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/actions/comment.js:90:30: Array.prototype.map() expects a return value from arrow function.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/actions/labels.js:56:23: Array.prototype.map() expects a return value from arrow function.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/actions/merge.js:96:37: Array.prototype.map() expects a return value from arrow function.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/cache/cache.js:9:9: Unexpected var, use let or const instead.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/configuration/transformers/v1Config.js:104:11: Expected newline between consequent and alternate of ternary expression.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/approvals.js:95:7: Unnecessary try/catch wrapper.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/approvals.js:151:9: Expected newline between consequent and alternate of ternary expression.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/approvals.js:162:9: Expected newline between consequent and alternate of ternary expression.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/deepValidation.js:1:28: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:1:26: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:2:23: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:3:28: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:4:32: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:5:35: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:6:37: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/gitPattern.js:83:17: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/owners.js:37:7: Unnecessary try/catch wrapper.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/owners.js:109:21: Use a regular expression literal instead of the 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/owners.js:109:32: Unexpected control character(s) in regular expression: \x01, \x08, \x0b, \x0c, \x0e, \x1f, \x01, \x09, \x0b, \x0c, \x0e, \x01, \x08, \x0b, \x0c, \x0e, \x1f, \x01, \x09, \x0b, \x0c, \x0e.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/teams.js:12:7: Unnecessary try/catch wrapper.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/options_processor/teams.js:32:9: Unnecessary try/catch wrapper.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/size.js:193:32: Regular expression literal is unnecessarily wrapped within a 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/size.js:194:33: Regular expression literal is unnecessarily wrapped within a 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/size.js:241:30: Regular expression literal is unnecessarily wrapped within a 'RegExp' constructor.
  /Users/empirl/Workspace/repo/github/mergeability/mergeable/lib/validators/stale.js:58:28: Array.prototype.map() expects a value to be returned at the end of arrow function.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mergeable@2.0.0 lint: `standard --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mergeable@2.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by quike** [comment]
The rule:

```
Use a regular expression literal instead of the 'RegExp' constructor.
```

I suggest the use of:

```
// eslint-disable-next-line prefer-regex-literals
```

to respect current code and avoid the change yet.

**Comment by quike** [comment]
The rule:

```
Array.prototype.map() expects a return value from arrow function.
```

I suggest the use of:

```
// eslint-disable-next-line array-callback-return
```

to respect current code and avoid the change yet.

https://eslint.org/docs/2.0.0/rules/array-callback-return

**Comment by quike** [comment]
@shine2lay @jusx is the project still active? Is there a way any other contributor could review PRs? Thanks.

**Review by shine2lay — APPROVED** [review]

**Pull request merged**
