### PR TITLE
docs: fix another typo in the commit check example

### PR DESCRIPTION
**Pull request by laughedelic**
I'm on a roll today! 😂 A follow up for #287

This one was worse because it it didn't fail the config validation, just failed the `commit` check itself and  I couldn't figure out why it's failing.

### CODE REVIEW

**Comment by shine2lay** [comment]
@laughedelic whoa, Nice! This is awesome! I guess because it's an optional field, it's just skips that option.

**Comment by laughedelic** [comment]
Yes, it would be nice to have stricter validation of the config, to report "unused" fields?

**Comment by shine2lay** [comment]
@laughedelic yes, i agree, i'll create an issue for that. Thanks again for the fix

**Comment by laughedelic** [comment]
Thanks! Also, is there a way to validate the config locally or remotely without committing it and trying out?

**Comment by shine2lay** [comment]
@laughedelic unfortunately no, you best you can do now is to create a PR with the new `mergeable.yml` config. Mergeable will read the new config from the PR instead of old config from the base branch.

**Comment by laughedelic** [comment]
Ok, thanks!

**Pull request merged**
