### PR TITLE
chore: add support for latest version of `probot`

### PR DESCRIPTION
**Pull request by tenshiAMD**
This is to support the latest version of `probot`. 

NOTE: @jusx and @shine2lay please let me join as one of the maintainers here 😄

### CODE REVIEW

**Comment by tenshiAMD** [comment]
@jusx @shine2lay gentle ping

**Comment by tenshiAMD** [comment]
@jusx @shine2lay please review this one

**Comment by jusx** [comment]
Hi @tenshiAMD -- happy to get this merged. Do you know the general benefits of upgrading?

**Review by jusx — APPROVED** [review]

**Comment by tenshiAMD** [comment]
@jusx Hi there. Thanks for reviewing my PR. I'm glad to help here. I think probot is more efficient and has a lot of important bug fixes from v11 to v12.

**Comment by tenshiAMD** [comment]
@jusx gentle ping 👋

**Comment by shine2lay** [comment]
will merge once CI passes

**Pull request merged**
