### PR TITLE
chore(deps): bump jest to latest v26.6 available version

### PR DESCRIPTION
**Pull request by quike**
- Bumps jest from 24.0.0 to 26.6.3: Current v24.0.0 was released over 2 years ago

https://www.npmjs.com/package/jest/v/26.6.3
https://www.npmjs.com/package/jest/v/24.0.0

- Bumps nock from 13.0.5 to 13.1.0

https://www.npmjs.com/package/nock/v/13.0.5
https://www.npmjs.com/package/nock/v/13.1.0

> NOTE: jest v27 introduces several breaking changes that require further analysis to fix unhandled promises due to a 401 error code throw by the mocked server.
https://github.com/facebook/jest/releases/tag/v27.0.0

@shine2lay @jusx

### CODE REVIEW

**Comment by quike** [comment]
```
----------------------------------------------|---------|----------|---------|---------|---------------------------------
File                                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s               
----------------------------------------------|---------|----------|---------|---------|---------------------------------
All files                                     |   90.58 |    83.64 |   90.74 |   91.25 |                                 
 lib                                          |   78.15 |    71.11 |   78.13 |      80 |                                 
  context.js                                  |     100 |       75 |     100 |     100 | 16                              
  eventAware.js                               |     100 |      100 |     100 |     100 |                                 
  logger.js                                   |       0 |        0 |       0 |       0 | 5-30                            
  mergeable.js                                |   72.92 |    57.14 |   63.64 |   77.78 | 22-34,92                        
  metaData.js                                 |     100 |      100 |     100 |     100 |                                 
  register.js                                 |   90.91 |       90 |     100 |   90.91 | 49,54,59                        
 lib/actions                                  |   91.56 |    76.56 |   87.32 |   91.89 |                                 
  action.js                                   |   89.47 |      100 |   66.67 |   89.47 | 12-15                           
  assign.js                                   |    91.3 |       50 |      80 |   94.74 | 18                              
  checks.js                                   |      94 |    83.33 |     100 |      94 | 16-17,31                        
  close.js                                    |     100 |      100 |      80 |     100 |                                 
  comment.js                                  |   92.31 |     62.5 |     100 |   91.67 | 37-46                           
  labels.js                                   |     100 |      100 |   90.91 |     100 |                                 
  merge.js                                    |    81.4 |    66.67 |   85.71 |   82.93 | 19,36-50,77                     
  request_review.js                           |    93.1 |      100 |    87.5 |   92.31 | 12-19                           
 lib/actions/handlebars                       |   70.83 |    28.57 |   66.67 |   70.83 |                                 
  populateTemplate.js                         |   70.83 |    28.57 |   66.67 |   70.83 | 5-7,19,29-33                    
 lib/actions/lib                              |     100 |      100 |     100 |     100 |                                 
  createCheckName.js                          |     100 |      100 |     100 |     100 |                                 
  searchAndReplaceSpecialAnnotation.js        |     100 |      100 |     100 |     100 |                                 
 lib/cache                                    |   58.33 |    33.33 |     100 |   58.33 |                                 
  cache.js                                    |   58.33 |    33.33 |     100 |   58.33 | 9-14                            
 lib/configuration                            |    95.5 |    90.79 |   94.44 |   97.12 |                                 
  configuration.js                            |    95.5 |    90.79 |   94.44 |   97.12 | 179-182                         
 lib/configuration/lib                        |     100 |      100 |     100 |     100 |                                 
  consts.js                                   |     100 |      100 |     100 |     100 |                                 
 lib/configuration/transformers               |   95.96 |    94.12 |      95 |   96.63 |                                 
  v1Config.js                                 |   97.67 |      100 |   91.67 |   97.62 | 5                               
  v2Config.js                                 |   94.64 |     90.7 |     100 |   95.74 | 21,29                           
 lib/errors                                   |     100 |      100 |     100 |     100 |                                 
  teamNotFoundError.js                        |     100 |      100 |     100 |     100 |                                 
  unSupportedSettingError.js                  |     100 |      100 |     100 |     100 |                                 
 lib/filters                                  |   96.59 |       90 |   94.12 |   96.55 |                                 
  and.js                                      |     100 |      100 |     100 |     100 |                                 
  author.js                                   |     100 |      100 |     100 |     100 |                                 
  filter.js                                   |   93.02 |     87.5 |   85.71 |   92.86 | 18,23,35                        
  or.js                                       |     100 |      100 |     100 |     100 |                                 
  repository.js                               |     100 |      100 |     100 |     100 |                                 
 lib/filters/lib                              |     100 |      100 |     100 |     100 |                                 
  andOrValidatorProcessor.js                  |     100 |      100 |     100 |     100 |                                 
 lib/filters/options_processor                |   88.68 |    65.38 |     100 |   88.46 |                                 
  name.js                                     |     100 |      100 |     100 |     100 |                                 
  options.js                                  |   90.48 |     62.5 |     100 |      90 | 40,46                           
  topics.js                                   |   77.78 |       40 |     100 |   77.78 | 20-22,31                        
  visibility.js                               |     100 |      100 |     100 |     100 |                                 
 lib/filters/options_processor/options        |      50 |      100 |      50 |      50 |                                 
  and.js                                      |       0 |      100 |       0 |       0 | 1-9                             
  must_exclude.js                             |     100 |      100 |     100 |     100 |                                 
  must_include.js                             |     100 |      100 |     100 |     100 |                                 
  or.js                                       |       0 |      100 |       0 |       0 | 1-9                             
 lib/filters/options_processor/options/lib    |     100 |      100 |     100 |     100 |                                 
  consolidateResults.js                       |     100 |      100 |     100 |     100 |                                 
  constructError.js                           |     100 |      100 |     100 |     100 |                                 
  constructOutput.js                          |     100 |      100 |     100 |     100 |                                 
 lib/flex                                     |      85 |    83.33 |     100 |      85 |                                 
  flex.js                                     |      85 |    83.33 |     100 |      85 | 29-37                           
 lib/flex/lib                                 |   83.89 |       60 |    87.5 |   83.69 |                                 
  createPromises.js                           |     100 |      100 |     100 |     100 |                                 
  getActionPromises.js                        |     100 |       50 |     100 |     100 | 5                               
  getFilterPromises.js                        |     100 |      100 |     100 |     100 |                                 
  getValidatorPromises.js                     |     100 |      100 |     100 |     100 |                                 
  logAndProcessConfigErrors.js                |   85.71 |       50 |     100 |   88.89 | 37-44                           
  processWorkflow.js                          |   77.27 |    56.67 |   78.57 |   76.19 | 21-37,48-73,80,85-86,94,139-158 
 lib/github                                   |   82.61 |    33.33 |     100 |   82.61 |                                 
  api.js                                      |   82.61 |    33.33 |     100 |   82.61 | 19-23                           
 lib/interceptors                             |   91.18 |    85.29 |   88.89 |      95 |                                 
  checkReRun.js                               |   91.67 |    85.71 |     100 |     100 | 20,26                           
  index.js                                    |     100 |      100 |     100 |     100 |                                 
  interceptor.js                              |      50 |      100 |       0 |      50 | 17                              
  milestoned.js                               |     100 |      100 |     100 |     100 |                                 
  push.js                                     |   89.66 |    78.57 |     100 |   92.31 | 26-27                           
 lib/settings                                 |   90.48 |    84.21 |      80 |   94.81 |                                 
  settings.js                                 |   90.48 |    84.21 |      80 |   94.81 | 71-72,117,122                   
 lib/settings/lib                             |     100 |      100 |     100 |     100 |                                 
  consts.js                                   |     100 |      100 |     100 |     100 |                                 
 lib/settings/transformers                    |     100 |      100 |     100 |     100 |                                 
  v1Settings.js                               |     100 |      100 |     100 |     100 |                                 
 lib/stats                                    |     100 |      100 |     100 |     100 |                                 
  extractValidationStats.js                   |     100 |      100 |     100 |     100 |                                 
  githubPrometheusStats.js                    |     100 |      100 |     100 |     100 |                                 
 lib/utils                                    |   15.38 |        0 |       0 |   15.38 |                                 
  githubRateLimitEndpoint.js                  |    8.33 |        0 |       0 |    8.33 | 2-20                            
  logTypes.js                                 |     100 |      100 |     100 |     100 |                                 
 lib/validators                               |   96.95 |    89.45 |   99.06 |   97.47 |                                 
  age.js                                      |     100 |      100 |     100 |     100 |                                 
  and.js                                      |     100 |      100 |     100 |     100 |                                 
  approvals.js                                |   93.94 |    89.83 |     100 |   93.75 | 98,133-138                      
  assignee.js                                 |     100 |      100 |     100 |     100 |                                 
  baseRef.js                                  |     100 |      100 |     100 |     100 |                                 
  changeset.js                                |     100 |      100 |     100 |     100 |                                 
  commit.js                                   |   95.12 |    86.36 |     100 |     100 | 37-38,82                        
  contents.js                                 |   95.65 |    83.33 |     100 |   97.56 | 96                              
  dependent.js                                |   96.97 |    90.91 |     100 |   96.88 | 42                              
  description.js                              |     100 |      100 |     100 |     100 |                                 
  headRef.js                                  |     100 |      100 |     100 |     100 |                                 
  label.js                                    |     100 |      100 |     100 |     100 |                                 
  milestone.js                                |     100 |      100 |     100 |     100 |                                 
  or.js                                       |     100 |      100 |     100 |     100 |                                 
  project.js                                  |   98.25 |    85.71 |     100 |   97.92 | 37                              
  size.js                                     |   97.14 |    86.54 |     100 |      98 | 161,224                         
  stale.js                                    |     100 |    93.48 |     100 |     100 | 53,57,60                        
  title.js                                    |     100 |      100 |     100 |     100 |                                 
  validator.js                                |   93.48 |    88.46 |   85.71 |   93.33 | 35,40,52                        
 lib/validators/lib                           |     100 |      100 |     100 |     100 |                                 
  andOrValidatorProcessor.js                  |     100 |      100 |     100 |     100 |                                 
 lib/validators/options_processor             |   79.57 |    60.87 |   85.37 |   81.74 |                                 
  assignees.js                                |     100 |      100 |     100 |     100 |                                 
  deepValidation.js                           |   83.33 |       50 |     100 |   82.61 | 27-37                           
  gitPattern.js                               |   98.57 |    84.38 |     100 |   98.55 | 88                              
  options.js                                  |     100 |      100 |     100 |     100 |                                 
  owners.js                                   |   79.31 |    55.56 |   69.23 |   81.48 | 40,62-65,80-81,87-93,103-104    
  requestedReviewers.js                       |     100 |      100 |     100 |     100 |                                 
  teams.js                                    |   44.64 |    23.08 |      60 |   48.98 | 24-41,48,65,72-95               
 lib/validators/options_processor/options     |   92.14 |    88.82 |     100 |   91.35 |                                 
  and.js                                      |     100 |      100 |     100 |     100 |                                 
  begins_with.js                              |      90 |       85 |     100 |   88.46 | 23,35,39                        
  ends_with.js                                |      90 |       85 |     100 |   88.46 | 23,35,39                        
  jira.js                                     |   83.87 |    81.82 |     100 |   83.33 | 24,29,38,64,69                  
  max.js                                      |     100 |      100 |     100 |     100 |                                 
  min.js                                      |   93.33 |    91.67 |     100 |   92.86 | 22                              
  must_exclude.js                             |   92.59 |    90.91 |     100 |   91.67 | 28,40                           
  must_include.js                             |   92.59 |    90.91 |     100 |   91.67 | 28,40                           
  no_empty.js                                 |   94.74 |     87.5 |     100 |   94.44 | 31                              
  or.js                                       |     100 |      100 |     100 |     100 |                                 
  required.js                                 |    96.3 |    90.91 |     100 |   95.83 | 14                              
 lib/validators/options_processor/options/lib |   98.15 |    97.06 |     100 |   98.15 |                                 
  andOrProcessor.js                           |   97.44 |    96.43 |     100 |   97.44 | 18                              
  consolidateResults.js                       |     100 |      100 |     100 |     100 |                                 
  constructErrorOutput.js                     |     100 |      100 |     100 |     100 |                                 
  constructOutput.js                          |     100 |      100 |     100 |     100 |                                 
----------------------------------------------|---------|----------|---------|---------|---------------------------------

Test Suites: 62 passed, 62 total
Tests:       418 passed, 418 total
Snapshots:   0 total
Time:        5.386 s
Ran all test suites.

```

**Comment by shine2lay** [comment]
@quike thanks for the PRs, both of us are a bit busy these days it seems. I'll try to review this over the weekend. sorry about delays

**Comment by shine2lay** [comment]
@quike please resolve conflict

**Review by shine2lay — APPROVED** [review]

**Comment by shine2lay** [comment]
The Tests run is stuck https://github.com/mergeability/mergeable/pull/555/checks?check_run_id=2921889723 , the run won't end

**Comment by quike** [comment]
```
❯ npm run test-coverage

> mergeable@2.0.0 test-coverage /Users/quike/Workspace/repo/github/quike/mergeable
> NODE_ENV=test standard && jest --collectCoverage && codecov

 PASS  __tests__/unit/validators/options_processor/options.test.js
 PASS  __tests__/unit/settings/settings.test.js
 PASS  __tests__/unit/validators/dependent.test.js
 PASS  __tests__/unit/configuration/transformers/v1Config.test.js
 PASS  __tests__/unit/validators/options_processor/owners.test.js
 PASS  __tests__/unit/validators/options_processor/options/jira.test.js
 PASS  __tests__/unit/validators/approvals.test.js
 PASS  __tests__/unit/validators/size.test.js
 PASS  __tests__/unit/configuration/configuration.test.js
 PASS  __tests__/unit/validators/and.test.js
 PASS  __tests__/unit/validators/stale.test.js
 PASS  __tests__/unit/validators/or.test.js
 PASS  __tests__/unit/filters/and.test.js
 PASS  __tests__/unit/validators/label.test.js
 PASS  __tests__/unit/actions/labels.test.js
 PASS  scheduler/test.js
 PASS  __tests__/unit/actions/checks.test.js
 PASS  __tests__/unit/filters/or.test.js
 PASS  __tests__/unit/validators/commit.test.js
 PASS  __tests__/unit/interceptors/push.test.js
 PASS  __tests__/unit/filters/repository.test.js
 PASS  __tests__/unit/mergeable.test.js
 PASS  __tests__/unit/validators/contents.test.js
 PASS  __tests__/unit/actions/merge.test.js
 PASS  __tests__/unit/validators/project.test.js
 PASS  __tests__/unit/validators/options_processor/teams.test.js
 PASS  __tests__/unit/filters/author.test.js
 PASS  __tests__/unit/flex/flex.test.js
 PASS  __tests__/unit/actions/comment.test.js
 PASS  __tests__/unit/validators/title.test.js
 PASS  __tests__/unit/actions/action.test.js
 PASS  __tests__/unit/validators/changeset.test.js
 PASS  __tests__/unit/interceptors/milestoned.test.js
 PASS  __tests__/unit/validators/assignee.test.js
 PASS  __tests__/unit/validators/description.test.js
 PASS  __tests__/unit/validators/milestone.test.js
 PASS  __tests__/unit/validators/headRef.test.js
 PASS  __tests__/unit/validators/baseRef.test.js
 PASS  __tests__/unit/validators/options_processor/options/and.test.js
 PASS  __tests__/unit/validators/options_processor/options/lib/consolidateResults.test.js
 PASS  __tests__/unit/validators/age.test.js
 PASS  __tests__/unit/actions/lib/searchAndReplaceSpecialAnnotation.test.js
 PASS  __tests__/unit/validators/options_processor/assignees.test.js
 PASS  __tests__/unit/validators/options_processor/options/required.test.js
 PASS  __tests__/unit/actions/assign.test.js
 PASS  __tests__/unit/configuration/transformers/v2Config.test.js
 PASS  __tests__/unit/actions/close.test.js
 PASS  __tests__/unit/validators/options_processor/options/min.test.js
 PASS  __tests__/unit/actions/request_review.test.js
 PASS  __tests__/unit/validators/options_processor/options/must_include.test.js
 PASS  __tests__/unit/filters/filter.test.js
 PASS  __tests__/unit/validators/options_processor/options/or.test.js
 PASS  __tests__/unit/validators/options_processor/options/max.test.js
 PASS  __tests__/unit/validators/options_processor/options/no_empty.test.js
(node:20180) UnhandledPromiseRejectionWarning: HttpError: A JSON web token could not be decoded
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  __tests__/unit/interceptors/checkReRun.test.js
 PASS  __tests__/unit/validators/options_processor/options/must_exclude.test.js
 PASS  __tests__/unit/validators/options_processor/options/begins_with.test.js
 PASS  __tests__/unit/filters/payload.test.js
 PASS  __tests__/unit/validators/options_processor/options/ends_with.test.js
 PASS  __tests__/unit/metaData.test.js
 PASS  __tests__/unit/validators/validator.test.js
 PASS  __tests__/unit/github/api.test.js
 PASS  __tests__/e2e/smoke.test.js
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
----------------------------------------------|---------|----------|---------|---------|---------------------------------
File                                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s               
----------------------------------------------|---------|----------|---------|---------|---------------------------------
All files                                     |   90.86 |    83.77 |   90.89 |   91.53 |                                 
 lib                                          |   78.51 |    72.34 |   78.13 |   80.34 |                                 
  context.js                                  |     100 |       75 |     100 |     100 | 16                              
  eventAware.js                               |     100 |      100 |     100 |     100 |                                 
  logger.js                                   |       0 |        0 |       0 |       0 | 5-30                            
  mergeable.js                                |   72.92 |    57.14 |   63.64 |   77.78 | 22-34,92                        
  metaData.js                                 |     100 |      100 |     100 |     100 |                                 
  register.js                                 |   90.91 |       90 |     100 |   90.91 | 51,56,61                        
 lib/actions                                  |   91.63 |    76.56 |   87.32 |   91.96 |                                 
  action.js                                   |   90.48 |      100 |   66.67 |   90.48 | 14-18                           
  assign.js                                   |    91.3 |       50 |      80 |   94.74 | 18                              
  checks.js                                   |      94 |    83.33 |     100 |      94 | 16-17,31                        
  close.js                                    |     100 |      100 |      80 |     100 |                                 
  comment.js                                  |   92.31 |     62.5 |     100 |   91.67 | 37-46                           
  labels.js                                   |     100 |      100 |   90.91 |     100 |                                 
  merge.js                                    |    81.4 |    66.67 |   85.71 |   82.93 | 19,36-50,77                     
  request_review.js                           |    93.1 |      100 |    87.5 |   92.31 | 12-19                           
 lib/actions/handlebars                       |   70.83 |    28.57 |   66.67 |   70.83 |                                 
  populateTemplate.js                         |   70.83 |    28.57 |   66.67 |   70.83 | 5-7,19,29-33                    
 lib/actions/lib                              |     100 |      100 |     100 |     100 |                                 
  createCheckName.js                          |     100 |      100 |     100 |     100 |                                 
  searchAndReplaceSpecialAnnotation.js        |     100 |      100 |     100 |     100 |                                 
 lib/cache                                    |   58.33 |    33.33 |     100 |   58.33 |                                 
  cache.js                                    |   58.33 |    33.33 |     100 |   58.33 | 9-15                            
 lib/configuration                            |    95.5 |    90.79 |   94.44 |   97.12 |                                 
  configuration.js                            |    95.5 |    90.79 |   94.44 |   97.12 | 179-182                         
 lib/configuration/lib                        |     100 |      100 |     100 |     100 |                                 
  consts.js                                   |     100 |      100 |     100 |     100 |                                 
 lib/configuration/transformers               |   95.96 |    94.12 |      95 |   96.63 |                                 
  v1Config.js                                 |   97.67 |      100 |   91.67 |   97.62 | 5                               
  v2Config.js                                 |   94.64 |     90.7 |     100 |   95.74 | 21,29                           
 lib/errors                                   |     100 |      100 |     100 |     100 |                                 
  teamNotFoundError.js                        |     100 |      100 |     100 |     100 |                                 
  unSupportedSettingError.js                  |     100 |      100 |     100 |     100 |                                 
 lib/filters                                  |   97.27 |    91.89 |   95.45 |   97.22 |                                 
  and.js                                      |     100 |      100 |     100 |     100 |                                 
  author.js                                   |     100 |      100 |     100 |     100 |                                 
  filter.js                                   |   93.02 |     87.5 |   85.71 |   92.86 | 18,23,35                        
  or.js                                       |     100 |      100 |     100 |     100 |                                 
  payload.js                                  |     100 |      100 |     100 |     100 |                                 
  repository.js                               |     100 |      100 |     100 |     100 |                                 
 lib/filters/lib                              |     100 |      100 |     100 |     100 |                                 
  andOrValidatorProcessor.js                  |     100 |      100 |     100 |     100 |                                 
 lib/filters/options_processor                |   88.68 |    65.38 |     100 |   88.46 |                                 
  name.js                                     |     100 |      100 |     100 |     100 |                                 
  options.js                                  |   90.48 |     62.5 |     100 |      90 | 40,46                           
  topics.js                                   |   77.78 |       40 |     100 |   77.78 | 20-22,31                        
  visibility.js                               |     100 |      100 |     100 |     100 |                                 
 lib/filters/options_processor/options        |      50 |      100 |      50 |      50 |                                 
  and.js                                      |       0 |      100 |       0 |       0 | 1-9                             
  must_exclude.js                             |     100 |      100 |     100 |     100 |                                 
  must_include.js                             |     100 |      100 |     100 |     100 |                                 
  or.js                                       |       0 |      100 |       0 |       0 | 1-9                             
 lib/filters/options_processor/options/lib    |     100 |      100 |     100 |     100 |                                 
  consolidateResults.js                       |     100 |      100 |     100 |     100 |                                 
  constructError.js                           |     100 |      100 |     100 |     100 |                                 
  constructOutput.js                          |     100 |      100 |     100 |     100 |                                 
 lib/flex                                     |      85 |    83.33 |     100 |      85 |                                 
  flex.js                                     |      85 |    83.33 |     100 |      85 | 29-37                           
 lib/flex/lib                                 |   83.89 |       60 |    87.5 |   83.69 |                                 
  createPromises.js                           |     100 |      100 |     100 |     100 |                                 
  getActionPromises.js                        |     100 |       50 |     100 |     100 | 5                               
  getFilterPromises.js                        |     100 |      100 |     100 |     100 |                                 
  getValidatorPromises.js                     |     100 |      100 |     100 |     100 |                                 
  logAndProcessConfigErrors.js                |   85.71 |       50 |     100 |   88.89 | 37-44                           
  processWorkflow.js                          |   77.27 |    56.67 |   78.57 |   76.19 | 21-37,48-73,80,85-86,94,139-158 
 lib/github                                   |   87.88 |    33.33 |     100 |   87.88 |                                 
  api.js                                      |   87.88 |    33.33 |     100 |   87.88 | 19-23                           
 lib/interceptors                             |   91.18 |    85.29 |   88.89 |      95 |                                 
  checkReRun.js                               |   91.67 |    85.71 |     100 |     100 | 20,26                           
  index.js                                    |     100 |      100 |     100 |     100 |                                 
  interceptor.js                              |      50 |      100 |       0 |      50 | 17                              
  milestoned.js                               |     100 |      100 |     100 |     100 |                                 
  push.js                                     |   89.66 |    78.57 |     100 |   92.31 | 26-27                           
 lib/settings                                 |   90.48 |    84.21 |      80 |   94.81 |                                 
  settings.js                                 |   90.48 |    84.21 |      80 |   94.81 | 71-72,117,122                   
 lib/settings/lib                             |     100 |      100 |     100 |     100 |                                 
  consts.js                                   |     100 |      100 |     100 |     100 |                                 
 lib/settings/transformers                    |     100 |      100 |     100 |     100 |                                 
  v1Settings.js                               |     100 |      100 |     100 |     100 |                                 
 lib/stats                                    |     100 |      100 |     100 |     100 |                                 
  extractValidationStats.js                   |     100 |      100 |     100 |     100 |                                 
  githubPrometheusStats.js                    |     100 |      100 |     100 |     100 |                                 
 lib/utils                                    |   15.38 |        0 |       0 |   15.38 |                                 
  githubRateLimitEndpoint.js                  |    8.33 |        0 |       0 |    8.33 | 2-20                            
  logTypes.js                                 |     100 |      100 |     100 |     100 |                                 
 lib/validators                               |   97.11 |    89.45 |   99.06 |   97.64 |                                 
  age.js                                      |     100 |      100 |     100 |     100 |                                 
  and.js                                      |     100 |      100 |     100 |     100 |                                 
  approvals.js                                |   94.85 |    89.83 |     100 |   94.68 | 144-149                         
  assignee.js                                 |     100 |      100 |     100 |     100 |                                 
  baseRef.js                                  |     100 |      100 |     100 |     100 |                                 
  changeset.js                                |     100 |      100 |     100 |     100 |                                 
  commit.js                                   |   95.12 |    86.36 |     100 |     100 | 37-38,82                        
  contents.js                                 |   95.65 |    83.33 |     100 |   97.56 | 96                              
  dependent.js                                |   96.97 |    90.91 |     100 |   96.88 | 42                              
  description.js                              |     100 |      100 |     100 |     100 |                                 
  headRef.js                                  |     100 |      100 |     100 |     100 |                                 
  label.js                                    |     100 |      100 |     100 |     100 |                                 
  milestone.js                                |     100 |      100 |     100 |     100 |                                 
  or.js                                       |     100 |      100 |     100 |     100 |                                 
  project.js                                  |   98.25 |    85.71 |     100 |   97.92 | 37                              
  size.js                                     |   97.14 |    86.54 |     100 |      98 | 161,226                         
  stale.js                                    |     100 |    93.48 |     100 |     100 | 53,57,61                        
  title.js                                    |     100 |      100 |     100 |     100 |                                 
  validator.js                                |   93.48 |    88.46 |   85.71 |   93.33 | 35,40,52                        
 lib/validators/lib                           |     100 |      100 |     100 |     100 |                                 
  andOrValidatorProcessor.js                  |     100 |      100 |     100 |     100 |                                 
 lib/validators/options_processor             |   80.35 |    60.87 |   85.37 |   82.63 |                                 
  assignees.js                                |     100 |      100 |     100 |     100 |                                 
  deepValidation.js                           |   83.33 |       50 |     100 |   82.61 | 28-38                           
  gitPattern.js                               |   98.57 |    84.38 |     100 |   98.55 | 95                              
  options.js                                  |     100 |      100 |     100 |     100 |                                 
  owners.js                                   |   80.36 |    55.56 |   69.23 |   82.69 | 58-61,76-77,83-89,99-100        
  requestedReviewers.js                       |     100 |      100 |     100 |     100 |                                 
  teams.js                                    |   44.23 |    23.08 |      60 |   48.89 | 19-31,38,55,62-85               
 lib/validators/options_processor/options     |   92.14 |    88.82 |     100 |   91.35 |                                 
  and.js                                      |     100 |      100 |     100 |     100 |                                 
  begins_with.js                              |      90 |       85 |     100 |   88.46 | 23,35,39                        
  ends_with.js                                |      90 |       85 |     100 |   88.46 | 23,35,39                        
  jira.js                                     |   83.87 |    81.82 |     100 |   83.33 | 24,29,38,64,69                  
  max.js                                      |     100 |      100 |     100 |     100 |                                 
  min.js                                      |   93.33 |    91.67 |     100 |   92.86 | 22                              
  must_exclude.js                             |   92.59 |    90.91 |     100 |   91.67 | 28,40                           
  must_include.js                             |   92.59 |    90.91 |     100 |   91.67 | 28,40                           
  no_empty.js                                 |   94.74 |     87.5 |     100 |   94.44 | 31                              
  or.js                                       |     100 |      100 |     100 |     100 |                                 
  required.js                                 |    96.3 |    90.91 |     100 |   95.83 | 14                              
 lib/validators/options_processor/options/lib |   98.15 |    97.06 |     100 |   98.15 |                                 
  andOrProcessor.js                           |   97.44 |    96.43 |     100 |   97.44 | 18                              
  consolidateResults.js                       |     100 |      100 |     100 |     100 |                                 
  constructErrorOutput.js                     |     100 |      100 |     100 |     100 |                                 
  constructOutput.js                          |     100 |      100 |     100 |     100 |                                 
----------------------------------------------|---------|----------|---------|---------|---------------------------------

Test Suites: 63 passed, 63 total
Tests:       424 passed, 424 total
Snapshots:   0 total
Time:        6.433 s
Ran all test suites.
```

**Comment by quike** [comment]
thanks @shine2lay do we know why is that stuck? I am not allowed to see the logs.

Screen Shot 2021-06-26 at 2 03 47 PM

**Comment by shine2lay** [comment]
@quike i see this line 
`A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.` in your comment of `npm run test-coverage` I believe the test is hanged because of it

**Comment by quike** [comment]
```
> mergeable@2.0.0 test /Users/empirl/Workspace/repo/github/quike/mergeable
> NODE_ENV=test jest && standard

 PASS  __tests__/unit/validators/options_processor/owners.test.js
 PASS  __tests__/unit/validators/options_processor/options/jira.test.js
 PASS  __tests__/unit/filters/repository.test.js
 PASS  __tests__/unit/filters/and.test.js
 PASS  __tests__/unit/validators/size.test.js
 PASS  __tests__/unit/configuration/configuration.test.js
 PASS  __tests__/unit/validators/approvals.test.js
 PASS  __tests__/unit/validators/stale.test.js
 PASS  __tests__/unit/mergeable.test.js
 PASS  __tests__/unit/actions/labels.test.js
 PASS  __tests__/unit/configuration/transformers/v1Config.test.js
 PASS  __tests__/unit/validators/and.test.js
 PASS  __tests__/unit/interceptors/push.test.js
 PASS  __tests__/unit/settings/settings.test.js
 PASS  __tests__/unit/flex/flex.test.js
 PASS  __tests__/unit/validators/dependent.test.js
 PASS  scheduler/test.js
 PASS  __tests__/unit/filters/or.test.js
 PASS  __tests__/unit/actions/checks.test.js
 PASS  __tests__/unit/actions/comment.test.js
 PASS  __tests__/unit/validators/title.test.js
 PASS  __tests__/unit/validators/label.test.js
 PASS  __tests__/unit/validators/commit.test.js
 PASS  __tests__/unit/validators/age.test.js
 PASS  __tests__/unit/actions/assign.test.js
 PASS  __tests__/unit/validators/baseRef.test.js
 PASS  __tests__/unit/validators/or.test.js
 PASS  __tests__/unit/validators/description.test.js
 PASS  __tests__/unit/validators/changeset.test.js
 PASS  __tests__/unit/validators/assignee.test.js
 PASS  __tests__/unit/validators/headRef.test.js
 PASS  __tests__/unit/github/api.test.js
 PASS  __tests__/unit/filters/author.test.js
 PASS  __tests__/unit/validators/contents.test.js
 PASS  __tests__/unit/validators/project.test.js
 PASS  __tests__/unit/actions/action.test.js
 PASS  __tests__/unit/actions/merge.test.js
 PASS  __tests__/unit/actions/close.test.js
 PASS  __tests__/unit/configuration/transformers/v2Config.test.js
 PASS  __tests__/unit/validators/options_processor/teams.test.js
 PASS  __tests__/unit/validators/milestone.test.js
 PASS  __tests__/unit/actions/request_review.test.js
 PASS  __tests__/unit/validators/options_processor/assignees.test.js
 PASS  __tests__/unit/interceptors/checkReRun.test.js
 PASS  __tests__/unit/interceptors/milestoned.test.js
 PASS  __tests__/unit/validators/validator.test.js
 PASS  __tests__/unit/validators/options_processor/options/and.test.js
 PASS  __tests__/unit/validators/options_processor/options.test.js
 PASS  __tests__/unit/actions/lib/searchAndReplaceSpecialAnnotation.test.js
 PASS  __tests__/unit/filters/filter.test.js
 PASS  __tests__/unit/filters/payload.test.js
 PASS  __tests__/unit/validators/options_processor/options/or.test.js
 PASS  __tests__/unit/validators/options_processor/options/must_exclude.test.js
 PASS  __tests__/unit/metaData.test.js
 PASS  __tests__/unit/validators/options_processor/options/must_include.test.js
 PASS  __tests__/unit/validators/options_processor/options/max.test.js
 PASS  __tests__/unit/validators/options_processor/options/required.test.js
 PASS  __tests__/unit/validators/options_processor/options/ends_with.test.js
 PASS  __tests__/unit/validators/options_processor/options/min.test.js
 PASS  __tests__/unit/validators/options_processor/options/begins_with.test.js
 PASS  __tests__/unit/validators/options_processor/options/lib/consolidateResults.test.js
 PASS  __tests__/unit/validators/options_processor/options/no_empty.test.js
 PASS  __tests__/e2e/smoke.test.js (6.01 s)

Test Suites: 63 passed, 63 total
Tests:       424 passed, 424 total
Snapshots:   0 total
Time:        8.096 s
Ran all test suites.
```

**Comment by quike** [comment]
@shine2lay jest v27 introduces several breaking changes that require further analysis to fix unhandled promises due to a 401 error code throw by the mocked server.
https://github.com/facebook/jest/releases/tag/v27.0.0

**Comment by quike** [comment]
@shine2lay any chance you could take a look to this one to get merge?

**Pull request merged**
