### PR TITLE
feat: add `name` sub option to `repository` filter

### PR DESCRIPTION
**Pull request by shine2lay**
sample config
```
- do: repository
        name:
          must_include:
            regex: 'my-repo-name'
          must_exclude:
            regex: 'other-repo-name'
```

https://github.com/mergeability/mergeable/issues/509#issuecomment-782806518

### CODE REVIEW

**Review by jusx — COMMENTED** [review]
If this is a new feature, would it make sense to add user documentation as well?

**Comment by shine2lay** [comment]
> If this is a new feature, would it make sense to add user documentation as well?

I've already added documentation to the PR

**Review by jusx — APPROVED** [review]
I am unaware of a specific use-case where this would be useful but code wise it looks fine.

**Comment by shine2lay** [comment]
one use case that comes to mind where this could be useful is in org wide config file, they can have multiple generic recipes that applies to repos that `includes/excludes` specific names

**Pull request merged**
