### PR TITLE
docs: added options to docs

### PR DESCRIPTION
**Pull request by iammuho**
This PR adds docs for validator options.

Sample SS:

Screenshot 2021-01-29 at 11 06 05
Screenshot 2021-01-29 at 11 06 23

### CODE REVIEW

**Review by jusx — COMMENTED** [review]
This looks good. Just a suggestion that perhaps it will be helpful if under the "Supported Validators" where we list the validators we can link to the validators' respective docs. What do you think?

Will you be adding `jira` here?

**Comment by iammuho** [comment]
Hey @jusx , yeah you just merged the JIRA so now I'll add the jira too. And I'll check linking!

**Comment by iammuho** [comment]
Hey @jusx , I've looked at linking the highlighted sources part but I couldn't manage it and found out this plugin https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html which we might need to enable. Can you check this ?

**Review by shine2lay — APPROVED** [review]
LGTM

**Pull request merged**
