### PR TITLE
feat: fill in missing param for `checks` by using default values

### PR DESCRIPTION
**Pull request by shine2lay**
Context

When user provide partial parameter list for checks option, fill in the rest using default values

for more context, see https://github.com/mergeability/mergeable/issues/233#issuecomment-632211789

### CODE REVIEW

**Comment by shine2lay** [comment]
I took that comment to mean use default if field is missing in general for `checks`. i.e if they don't provide `summary` field, use default also as well. Do you think we should leave it at `title` only?

**Comment by jusx** [comment]
> I took that comment to mean use default if field is missing in general for `checks`. i.e if they don't provide `summary` field, use default also as well. Do you think we should leave it at `title` only?

The original issue and use case was around lack of feedback when a required property is not specified and the PR check hanging. For the check action, I suggest we:

1. default any GH APi required fields when not specified.
2. Update the docs about this behavior.

**Comment by shine2lay** [comment]
Ok, i'll fix it

**Comment by shine2lay** [comment]
@jusx  PTAL

**Pull request merged**
